courses_data = {
    1: {
        "name_en": "GRAPHIC DESIGN & UX/UI DESIGN",
        "name_tg": "КУРСИ GRAPHIC DESIGN & UX/UI DESIGN",
        "name_ru": "ГРАФИЧЕСКИЙ ДИЗАЙН И UX/UI ДИЗАЙН",
        "what_you_learn_en": "- Photoshop\n- CorelDraw\n- Illustrator\n- Figma",
        "what_you_learn_tg": "- Photoshop\n- CorelDraw\n- Illustrator\n- Figma",
        "what_you_learn_ru": "- Photoshop\n- CorelDraw\n- Illustrator\n- Figma",
        "duration_en": "4 months",
        "duration_tg": "4 моҳ",
        "duration_ru": "4 месяца",
        "schedule_en": "16:00 - 18:00 | 18:00 - 20:00",
        "schedule_tg": "16:00 - 18:00 | 18:00 - 20:00",
        "schedule_ru": "16:00 - 18:00 | 18:00 - 20:00",
        "emoji": "🎨"
    },
    2: {
        "name_en": "Programming for Children (7-13 years)",
        "name_tg": "БАРНОМАСОЗЙ БАРОИ КУДАКОН (АЗ 7 ТО 13 СОЛА)",
        "name_ru": "Программирование для детей (7-13 лет)",
        "what_you_learn_en": "1. Programming basics\n2. Math and Logic\n3. English for programming\n4. Scratch\n5. HTML & CSS",
        "what_you_learn_tg": "1. Асосҳои барномасозӣ\n2. Математика ва мантиқ\n3. Англисӣ барои барномасозӣ\n4. Scratch\n5. HTML & CSS",
        "what_you_learn_ru": "1. Основы программирования\n2. Математика и логика\n3. Английский для программирования\n4. Scratch\n5. HTML & CSS",
        "duration_en": "8 months",
        "duration_tg": "8 моҳ",
        "duration_ru": "8 месяцев",
        "schedule_en": "10:00 - 11:30 | 14:00 - 15:30",
        "schedule_tg": "10:00 - 11:30 | 14:00 - 15:30",
        "schedule_ru": "10:00 - 11:30 | 14:00 - 15:30",
        "emoji": "👶"
    },
    3: {
        "name_en": "10/10 Online Programming",
        "name_tg": "КУРСИ БАРНОМАСОЗӢ ДАР ФОРМАТИ ОНЛАЙН 10/10",
        "name_ru": "Программирование в формате 10/10 (Онлайн)",
        "what_you_learn_en": "- C++\n- HTML/CSS\n- Frontend (JavaScript, React, TypeScript)\n- Backend (C#, .NET, PostgreSQL)",
        "what_you_learn_tg": "- C++\n- HTML/CSS\n- Frontend (JavaScript, React, TypeScript)\n- Backend (C#, .NET, PostgreSQL)",
        "what_you_learn_ru": "- C++\n- HTML/CSS\n- Frontend (JavaScript, React, TypeScript)\n- Backend (C#, .NET, PostgreSQL)",
        "duration_en": "Varies by module",
        "duration_tg": "Вобаста ба модул",
        "duration_ru": "Зависит от модуля",
        "schedule_en": "Flexible schedule",
        "schedule_tg": "Флексӣ",
        "schedule_ru": "Гибкий график",
        "emoji": "💻"
    },
    4: {
        "name_en": "Computer Basics for Employees",
        "name_tg": "АСОСҲОИ КОМПЮТЕР БАРОИ КОРМАНДОН",
        "name_ru": "Основы компьютера для сотрудников",
        "what_you_learn_en": "1. Office software (Word, Excel, PowerPoint)\n2. Google Docs and Canva\n3. Keyboard skills\n4. Using ChatGPT",
        "what_you_learn_tg": "1. Барномаҳои офис (Word, Excel, PowerPoint)\n2. Google Docs ва Canva\n3. Кор бо клавиатура\n4. Истифодаи ChatGPT",
        "what_you_learn_ru": "1. Офисные программы (Word, Excel, PowerPoint)\n2. Google Docs и Canva\n3. Работа с клавиатурой\n4. Использование ChatGPT",
        "duration_en": "1 month",
        "duration_tg": "1 моҳ",
        "duration_ru": "1 месяц",
        "schedule_en": "14:00 - 16:00 | 18:00 - 20:00",
        "schedule_tg": "14:00 - 16:00 | 18:00 - 20:00",
        "schedule_ru": "14:00 - 16:00 | 18:00 - 20:00",
        "emoji": "🏢"
    },
    5: {
        "name_en": "C# from Scratch",
        "name_tg": "КУРСИ C# (АЗ НОЛ)",
        "name_ru": "C# с нуля",
        "what_you_learn_en": "- C#\n- PostgreSQL\n- .NET\n- Clean Architecture",
        "what_you_learn_tg": "- C#\n- PostgreSQL\n- .NET\n- Clean Architecture",
        "what_you_learn_ru": "- C#\n- PostgreSQL\n- .NET\n- Чистая архитектура",
        "duration_en": "4 months",
        "duration_tg": "4 моҳ",
        "duration_ru": "4 месяца",
        "schedule_en": "16:00 - 18:00 | 18:00 - 20:00",
        "schedule_tg": "16:00 - 18:00 | 18:00 - 20:00",
        "schedule_ru": "16:00 - 18:00 | 18:00 - 20:00",
        "emoji": "♯"
    },
    6: {
        "name_en": "Mobile Development (Flutter)",
        "name_tg": "КУРСИ MOBILE DEVELOPMENT",
        "name_ru": "Мобильная разработка (Flutter)",
        "what_you_learn_en": "- Dart\n- Flutter\n- State management\n- Clean Architecture",
        "what_you_learn_tg": "- Dart\n- Flutter\n- State management\n- Clean Architecture",
        "what_you_learn_ru": "- Dart\n- Flutter\n- Управление состоянием\n- Чистая архитектура",
        "duration_en": "4 months",
        "duration_tg": "4 моҳ",
        "duration_ru": "4 месяца",
        "schedule_en": "18:00 | 20:00",
        "schedule_tg": "18:00 | 20:00",
        "schedule_ru": "18:00 | 20:00",
        "emoji": "📱"
    },
    7: {
        "name_en": "Frontend Development",
        "name_tg": "FRONTEND",
        "name_ru": "Фронтенд разработка",
        "what_you_learn_en": "- JavaScript\n- React\n- TypeScript\n- Next.js\n- Clean Architecture",
        "what_you_learn_tg": "- JavaScript\n- React\n- TypeScript\n- Next.js\n- Clean Architecture",
        "what_you_learn_ru": "- JavaScript\n- React\n- TypeScript\n- Next.js\n- Чистая архитектура",
        "duration_en": "5 months",
        "duration_tg": "5 моҳ",
        "duration_ru": "5 месяцев",
        "schedule_en": "16:00 - 18:00 | 18:00 - 20:00",
        "schedule_tg": "16:00 - 18:00 | 18:00 - 20:00",
        "schedule_ru": "16:00 - 18:00 | 18:00 - 20:00",
        "emoji": "🖥️"
    },
    8: {
        "name_en": "Python from Scratch",
        "name_tg": "КУРСИ PYTHON (АЗ НОЛ)",
        "name_ru": "Python с нуля",
        "what_you_learn_en": "- Python\n- PostgreSQL\n- Telegram bots\n- FastAPI\n- Django",
        "what_you_learn_tg": "- Python\n- PostgreSQL\n- Telegram bots\n- FastAPI\n- Django",
        "what_you_learn_ru": "- Python\n- PostgreSQL\n- Telegram боты\n- FastAPI\n- Django",
        "duration_en": "4 months",
        "duration_tg": "4 моҳ",
        "duration_ru": "4 месяца",
        "schedule_en": "16:00 - 18:00 | 18:00 - 20:00",
        "schedule_tg": "16:00 - 18:00 | 18:00 - 20:00",
        "schedule_ru": "16:00 - 18:00 | 18:00 - 20:00",
        "emoji": "🐍"
    },
    9: {
        "name_en": "Programming from Scratch (A0)",
        "name_tg": "БАРНОМАСОЗИ АЗ НОЛ (A0)",
        "name_ru": "Программирование с нуля (A0)",
        "what_you_learn_en": "- C++\n- HTML/CSS\n- GitHub & Functions",
        "what_you_learn_tg": "- C++\n- HTML/CSS\n- GitHub & Functions",
        "what_you_learn_ru": "- C++\n- HTML/CSS\n- GitHub & Функции",
        "duration_en": "3 months",
        "duration_tg": "3 моҳ",
        "duration_ru": "3 месяца",
        "schedule_en": "16:00 - 18:00 | 18:00 - 20:00",
        "schedule_tg": "16:00 - 18:00 | 18:00 - 20:00",
        "schedule_ru": "16:00 - 18:00 | 18:00 - 20:00",
        "emoji": "👨‍💻"
    }
}